Add 'project' target to Makefile
01org/CODK-M pull request #27
Opened 2016-10-07 01:28 UTC by eriknyquist

This target creates a new directory for a project, copies in blank
examples for both ARC & x86, and creates an env.sh script containing
the contents of zephyr-env.sh and new values for ARC/X86_PROJ_DIR.

@calvinatintel @bigdinotech please review.

2016-10-10 23:03 UTC, bigdinotech reviewed
+1

2016-10-10 23:44 UTC, eriknyquist commented
Let's let @calvinatintel try it out too before merging

2016-10-11 21:59 UTC, calvinatintel requested changes
1. help target should be updated
2. `make project` gives no output. Should there be a little walk through?
3. `env.sh` should be 755
4. Do I run `env.sh` or source it?

2016-10-11 22:07 UTC, eriknyquist commented
@calvinatintel 

1. Valid. Will update help target.
2. Valid. Will print out a little usage guide.
3. Current mode is fine, since it will be sourced not executed. But, I'll add a check to ensure it is not executed.
4. RTFM :)

2016-10-11 23:30 UTC, calvinatintel approved these changes

2016-10-12 16:48 UTC, merged